# Run11 Relaxed-Risk Training
Thin orchestration notebook for the canonical Run11 relaxed-risk alpha-generation training path. Durable logic lives in `src/config.py`, `src/notebook_helpers/tcn_phase1.py`, and the agent/env modules.

## 1) Colab Setup
Clone/sync the repo, clean previous outputs, install requirements, and verify GPU availability.

In [1]:
import gc
import os
import shutil
import subprocess
import sys
from pathlib import Path

TRAIN_REPO_URL = "https://github.com/Dave-DKings/tcn_tape_vectorized_version.git"
TRAIN_REPO_DIR = Path("/content/tcn_tape_vectorized_version_clean")
TRAIN_BRANCH = "feature/run9-alpha-overhaul-20260311"
INSTALL_REQUIREMENTS = True

def run(cmd):
    print("+", " ".join(map(str, cmd)))
    subprocess.run(cmd, check=True)

run(["git", "ls-remote", "--exit-code", "--heads", TRAIN_REPO_URL, TRAIN_BRANCH])

if not (TRAIN_REPO_DIR / ".git").exists():
    run(["git", "clone", "--branch", TRAIN_BRANCH, TRAIN_REPO_URL, str(TRAIN_REPO_DIR)])
else:
    run(["git", "-C", str(TRAIN_REPO_DIR), "fetch", "origin"])
    run(["git", "-C", str(TRAIN_REPO_DIR), "checkout", TRAIN_BRANCH])
    run(["git", "-C", str(TRAIN_REPO_DIR), "reset", "--hard", f"origin/{TRAIN_BRANCH}"])

purge_paths = [
    TRAIN_REPO_DIR / "tcn_fusion_results",
    TRAIN_REPO_DIR / "tcn_results",
    TRAIN_REPO_DIR / "tcn_att_results",
    TRAIN_REPO_DIR / "output_log",
    TRAIN_REPO_DIR / "output_logs",
    TRAIN_REPO_DIR / "data" / "phase1_preparation_artifacts",
    TRAIN_REPO_DIR / "data" / "master_features_NORMALIZED.csv",
    TRAIN_REPO_DIR / "data" / "daily_ohlcv_assets.csv",
    TRAIN_REPO_DIR / "data" / "processed_daily_macro_features.csv",
]

for path in purge_paths:
    if path.is_dir():
        shutil.rmtree(path, ignore_errors=True)
    elif path.exists():
        path.unlink()

for cache_dir in TRAIN_REPO_DIR.rglob("__pycache__"):
    shutil.rmtree(cache_dir, ignore_errors=True)

for ckpt_dir in TRAIN_REPO_DIR.rglob(".ipynb_checkpoints"):
    shutil.rmtree(ckpt_dir, ignore_errors=True)

for mod in list(sys.modules):
    if mod == "src" or mod.startswith("src."):
        del sys.modules[mod]

gc.collect()

os.chdir(TRAIN_REPO_DIR)
if str(TRAIN_REPO_DIR) not in sys.path:
    sys.path.insert(0, str(TRAIN_REPO_DIR))

if INSTALL_REQUIREMENTS:
    requirements_file = TRAIN_REPO_DIR / "requirements.txt"
    run([sys.executable, "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel"])
    run([sys.executable, "-m", "pip", "install", "-r", str(requirements_file)])

print("[OK] Repo synced:", TRAIN_REPO_DIR)
run(["git", "-C", str(TRAIN_REPO_DIR), "rev-parse", "--abbrev-ref", "HEAD"])
run(["git", "-C", str(TRAIN_REPO_DIR), "rev-parse", "HEAD"])
print("[OK] Requirements installed:", INSTALL_REQUIREMENTS)

+ git ls-remote --exit-code --heads https://github.com/Dave-DKings/tcn_tape_vectorized_version.git feature/run9-alpha-overhaul-20260311
+ git -C /content/tcn_tape_vectorized_version_clean fetch origin
+ git -C /content/tcn_tape_vectorized_version_clean checkout feature/run9-alpha-overhaul-20260311
+ git -C /content/tcn_tape_vectorized_version_clean reset --hard origin/feature/run9-alpha-overhaul-20260311
+ /usr/bin/python3 -m pip install --upgrade pip setuptools wheel
+ /usr/bin/python3 -m pip install -r /content/tcn_tape_vectorized_version_clean/requirements.txt
[OK] Repo synced: /content/tcn_tape_vectorized_version_clean
+ git -C /content/tcn_tape_vectorized_version_clean rev-parse --abbrev-ref HEAD
+ git -C /content/tcn_tape_vectorized_version_clean rev-parse HEAD
[OK] Requirements installed: True

In [2]:
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
print('TF GPUs:', gpus)
if not gpus:
    raise RuntimeError('No GPU visible to TensorFlow. In Colab: Runtime -> Change runtime type -> GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
tf.keras.mixed_precision.set_global_policy('float32')
print('Mixed precision policy:', tf.keras.mixed_precision.global_policy())

TF GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Mixed precision policy: <DTypePolicy "float32">

## 2) Imports
Import the canonical source helpers and training entrypoints.

In [3]:
from pathlib import Path

import pandas as pd
from IPython.display import display

from src.config import build_run11_relaxed_config, assert_run11_relaxed_config
from src.csv_logger import CSVLogger
from src.notebook_helpers.tcn_phase1 import prepare_phase1_dataset, run_experiment6_tape

RUN_ID = 'run11'
TRAIN_RANDOM_SEED = 42
ANALYSIS_END_DATE = None

## 3) Build Canonical Run11 Config and Dataset
Create the source-backed Run11 relaxed-risk config, assert no drift, and prepare the dataset once.

In [4]:
train_config = build_run11_relaxed_config('phase1', analysis_end_date=ANALYSIS_END_DATE)
assert_run11_relaxed_config(train_config)

tp = train_config['training_params']
ap = train_config['agent_params']
ppo = ap['ppo_params']
env = train_config['environment_params']

print('[Run11] Canonical relaxed-risk config ready')
print('  analysis_start_date =', train_config['ANALYSIS_START_DATE'])
print('  split_date =', train_config['TRAIN_TEST_SPLIT_DATE'])
print('  architecture =', ap['actor_critic_type'])
print('  regime_conditioning =', ap['regime_conditioning_enabled'])
print('  distributional_critic =', ap['distributional_critic_enabled'])
print('  cvar_advantage_weight =', ppo['cvar_advantage_weight'])
print('  lagrangian =', {
    'threshold': ppo['lagrangian_cvar_threshold'],
    'lr': ppo['lagrangian_cvar_lr'],
    'lambda_max': ppo['lagrangian_cvar_lambda_max'],
    'penalty_scale': ppo['lagrangian_cvar_penalty_scale'],
})
print('  drawdown =', {
    'target': env['drawdown_constraint']['target'],
    'tolerance': env['drawdown_constraint']['tolerance'],
    'penalty_coef': env['drawdown_constraint']['penalty_coef'],
    'lambda_carry_decay': env['drawdown_constraint']['lambda_carry_decay'],
    'terminal_gate_a_max_drawdown': env['tape_terminal_gate_a_max_drawdown'],
})
print('  turnover =', {
    'target': env['target_turnover'],
    'base_scalar': env['turnover_penalty_scalar'],
    'curriculum': tp['turnover_penalty_curriculum'],
})
print('  execution_beta =', {
    'train_curriculum': tp['action_execution_beta_curriculum'],
    'eval_beta': tp['evaluation_action_execution_beta'],
})
print('  dispersion =', {
    'hhi_coef': ppo['alpha_diversity_coef'],
    'dispersion_coef': ppo['alpha_dispersion_coef'],
    'dispersion_target_std': ppo['alpha_dispersion_target_std'],
})
print('  checkpointing =', {
    'periodic_every_steps': tp['periodic_checkpoint_every_steps'],
    'high_watermark_sharpe_threshold': tp['high_watermark_sharpe_threshold'],
    'high_watermark_max_drawdown_abs_threshold': tp['high_watermark_max_drawdown_abs_threshold'],
    'step_sharpe_threshold': tp['step_sharpe_checkpoint_threshold'],
})
print('  deterministic_validation =', tp['deterministic_validation_checkpointing_enabled'])
print('  training_early_stop =', tp.get('training_early_stop_enabled', False))

train_phase1_data = prepare_phase1_dataset(
    train_config,
    force_download=True,
    preparation_artifacts_dir=str(TRAIN_REPO_DIR / 'data_exports'),
)

actuarial_cols = [c for c in train_phase1_data.master_df.columns if str(c).startswith('Actuarial_')]
if actuarial_cols:
    raise RuntimeError(f'Actuarial columns should be absent for Run11: {actuarial_cols}')

alpha_ret_cols = [c for c in train_phase1_data.master_df.columns if str(c).startswith('AlphaRet_')]
expected_alpha_cols = {'AlphaRet_1d', 'AlphaRet_5d', 'AlphaRet_20d', 'AlphaRet_5d_Z', 'AlphaRet_20d_Z'}
missing_alpha_cols = sorted(list(expected_alpha_cols - set(alpha_ret_cols)))
if missing_alpha_cols:
    raise RuntimeError(f'Missing expected alpha-return columns: {missing_alpha_cols}')

fundamental_cols = [c for c in train_phase1_data.master_df.columns if str(c).startswith('Fundamental_')]
if fundamental_cols:
    raise RuntimeError(f'Fundamental columns should be absent: {fundamental_cols}')

print('[OK] Train shape:', train_phase1_data.train_df.shape)
print('[OK] Test shape:', train_phase1_data.test_df.shape)
print('[OK] Actuarial feature check passed: none present (disabled)')
print('[OK] Alpha-return feature check passed:', sorted(alpha_ret_cols)[:10])
print('[OK] Fundamental feature check passed: none present')

[Run10] Canonical config ready
  analysis_start_date = 2016-01-01
  split_date = 2021-12-31
  architecture = TCN_FUSION
  regime_conditioning = True
  distributional_critic = True
  cvar_advantage_weight = 0.1
  lagrangian = {'threshold': -0.025, 'lr': 0.004, 'lambda_max': 5.0, 'penalty_scale': 3.0}
  drawdown = {'target': 0.18, 'tolerance': -0.015, 'penalty_coef': 1.5, 'lambda_carry_decay': 0.75}
  dispersion = {'hhi_coef': 0.01, 'dispersion_coef': 0.05, 'dispersion_target_std': 0.07}
  deterministic_validation = False
  training_early_stop = True
📊 Loading raw market data...
   [OK] Raw data shape: (55043, 7)
   [OK] Date range: 2003-09-02 00:00:00 => 2025-08-29 00:00:00

[TOOL] Computing multi-horizon log returns: [1, 5, 10, 21]
   [OK] Shape after returns: (54833, 11)

📈 Calculating 21-day rolling statistics

🧮 Computing technical indicators

🕯️ Adding candlestick geometry features (if enabled)

📊 Computing dynamic covariance features

🎯 Adding regime awareness features
   [OK] Master DF shape: (54703, 38)
   [OK] Total features: 38

📊 Integrating fundamental features (if enabled)...
   [OK] Fundamental columns in dataset: 0 (enabled=False)

📊 Integrating macroeconomic features (if enabled)...
   [OK] Macro features added - 12 columns: ['SOFR_diff', 'DGS10_level', 'DGS10_diff', 'T10Y2Y_level', 'TIPS10Y_level', 'TIPS10Y_diff', 'BreakevenInf10Y_level', 'BreakevenInf10Y_diff', 'IG_Credit_zscore', 'HY_Credit_diff', 'HY_Credit_zscore', 'VIX_zscore']

📊 Integrating Alpha features (if enabled)...

📊 Integrating actuarial features (if enabled)...
   ℹ️ Actuarial features disabled by config.

[OK] Final master DF shape: (54703, 67)
   [OK] Total features: 67
🧭 Feature audit plan: exp6_feature_audit_20260221_v2 (allowlist enabled)
   active feature count (phase1): 60
   [OK] expected active features: 60

================================================================================
[SPLIT] FILTERING TO ANALYSIS PERIOD
================================================================================
   Filtering data to: 2016-01-01 => 2025-09-01
   [OK] Dates after filter: 2429 trading days
   [OK] Date range: 2016-01-04 00:00:00 to 2025-08-29 00:00:00
================================================================================
================================================================================
[SPLIT]  TIME-BASED TRAIN/TEST SPLIT (Fixed date: 2021-12-31)
   Train: 2016-01-04 => 2021-12-31 (1511 days, 6.0 years, 15110 rows)
   Test:  2022-01-03 => 2025-08-29 (918 days, 3.6 years, 9180 rows)
================================================================================

[TOOL] NORMALISING FEATURES (standard scaler)

💾 Saving NORMALISED master dataframe to '/content/tcn_tape_vectorized_version_clean/data/master_features_NORMALIZED.csv'

💾 Saved preparation artifacts:
   raw OHLCV: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_raw_ohlcv.csv
   full engineered: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_feature_engineered_full.csv
   analysis-window engineered: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_feature_engineered_analysis_window.csv
   normalized master: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_feature_engineered_normalized.csv
   train normalized: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_train_normalized.csv
   test normalized: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_test_normalized.csv
   scalers: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_scalers.joblib
   audit report: /content/tcn_tape_vectorized_version_clean/data_exports/phase1_prep_20260313_055108_preparation_audit.json
[OK] Train shape: (15110, 67)
[OK] Test shape: (9180, 67)
[OK] Actuarial feature check passed: none present (disabled)
[OK] Alpha-return feature check passed: ['AlphaRet_1d', 'AlphaRet_20d', 'AlphaRet_20d_Z', 'AlphaRet_5d', 'AlphaRet_5d_Z']
[OK] Fundamental feature check passed: none present

## 4) Run Training
Launch the canonical Run11 relaxed-risk training path.

In [5]:
RUN_TRAINING = True

if RUN_TRAINING:
    training_params = train_config['training_params']
    print('[START] Starting training')
    print('Architecture:', train_config['agent_params'].get('actor_critic_type'))
    print('max_total_timesteps:', training_params['max_total_timesteps'])
    print('num_parallel_envs:', training_params.get('num_parallel_envs', 1))

    train_experiment6 = run_experiment6_tape(
        phase1_data=train_phase1_data,
        config=train_config,
        random_seed=TRAIN_RANDOM_SEED,
        csv_logger_cls=CSVLogger,
        use_covariance=True,
        architecture=train_config['agent_params'].get('actor_critic_type'),
        timesteps_per_update=training_params.get('timesteps_per_ppo_update', 1008),
        max_total_timesteps=training_params['max_total_timesteps'],
    )

    print('[OK] Training complete')
    print('checkpoint_prefix:', train_experiment6.checkpoint_path)
else:
    print('[SKIP] RUN_TRAINING=False')

[START] Starting training
Architecture: TCN_FUSION
max_total_timesteps: 500000
num_parallel_envs: 4

================================================================================
EXPERIMENT 6: TCN_FUSION Enhanced + TAPE Three-Component
================================================================================
Architecture: TCN + Fusion
Results root: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results
Working dir: /content/tcn_tape_vectorized_version_clean
Covariance Features: Yes
🎯 REWARD SYSTEM: TAPE (Three-Component v3)
   Profile: BalancedGrowth
   Daily: Base + DSR/PBRS + Turnover_Proximity
   Terminal: mode=signed | baseline=0.20 | scalar=10.0 (clipped ±10.0)
   Gate A: enabled (Sharpe <= 0.00 or MDD >= 25.0% -> force non-positive terminal bonus)
   Neutral Band: enabled (±0.020 around baseline)
   [CYCLE] Profile Manager: disabled (static profile only)
[RAND] Experiment Seed: 6042 (Base: 42, Offset: 6000)
[OK] Features: Enhanced (includes 2 covariance eigenvalues)
   Eigenvalues: ['Covariance_Eigenvalue_0', 'Covariance_Eigenvalue_1']
   Train shape: (15110, 67)
   Test shape: (9180, 67)
   ℹ️ Actuarial features disabled by config.

🏗️ Creating THREE-COMPONENT TAPE v3 environments (with curriculum)...
   🎯 Reward System: TAPE (Three-Component v3)
   📊 Profile: BalancedGrowth
   ⚙️  Component 1: Base Reward (Net Return)
   ⚙️  Component 2: DSR/PBRS (window=60, scalar=2.00, gamma=0.99)
   ⚙️  Component 3: Turnover Proximity (target=0.35, band=±0.20, scalar=0.25 -> 0.55 => 0.75 => 0.90 => 1.00)
      ↳ Schedule: 0.25@0 => 0.55@100,000 => 0.75@200,000 => 0.90@300,000 => 1.00@400,000
   ⚙️  Component 4: Execution Inertia (beta=0.35 -> 0.45 => 0.55 => 0.60, w_exec=(1-β)w_prev + βw_raw)
      ↳ Schedule: 0.35@0 => 0.45@100,000 => 0.55@200,000 => 0.60@350,000
   ⚡ Parallel rollout envs: 4
      ↳ Vectorized rollout collection enabled
   🎁 Terminal: mode=signed, baseline=0.20, scalar=10.0 (clipped ±10.0)
   🟰 Neutral Band: enabled (±0.020 around baseline)
   🚦 Gate A: enabled (Sharpe <= 0.00, MDD >= 25.0%)
   [BRAIN] Credit Assignment: step reward is computed at each environment step
   [RCPT] Episode-End Handling: terminal TAPE bonus is added at episode completion only
   [OK] Retroactive episode-wide reward rescaling: disabled in notebook helper path
   🌊 DSR Regime Scaling: ENABLED | low_mult=0.3 (vol<0.12) | mid_mult=1.0 | high_mult=1.5 (vol>0.25)
   📈 Outperformance Bonus (SPY): ENABLED | scalar=3.0
   🔐 Lagrangian CVaR: ENABLED | threshold=-0.025 | lr=0.004 | lambda_max=5.0 | penalty_scale=3.0
   Tail-Aware Advantage: ENABLED | weight=0.1 | bottom_k=4
   Alpha Regularization: hhi_coef=0.01 | dispersion_coef=0.05 | target_std=0.07
   🧪 Aux Per-Asset Return Head: ENABLED | coef=0.35
   🔒 Dirichlet Alpha Cap: 16.0
   🔒 Drawdown dual controller (requested): target=18.00%, tolerance=-1.50% (trigger boundary ≈ 16.50%), lr=0.100, λ_init=0.50, λ_floor=0.00, λ_max=5.00, penalty_coef=1.50
   📐 Position constraints: max_single_asset=25%, min_cash=5%
   [DEBUG] Regime-balanced sampling: use_curriculum_learning=True, volatility_regime pre-existing=False
   🎲 Volatility regimes ready for sampling (computed):
      high_vol: 494 dates (32.7%)
      low_vol: 494 dates (32.7%)
      medium_vol: 523 dates (34.6%)
   🧭 Regime start buckets (train env):
      high_vol: 494 dates (32.7%)
      low_vol: 494 dates (32.7%)
      medium_vol: 523 dates (34.6%)
   [OK] Drawdown controller armed in env: target=18.00%, trigger=16.50%, λ_init=0.500, λ_floor=0.000, λ_max=5.00, penalty_coef=1.50
[OK] THREE-COMPONENT TAPE v3 Environments created:
   Training: 1511 days
   Parallel train env instances: 4
   Testing: 918 days

🤖 Creating TCN_FUSION agent with Dirichlet distribution for Exp 6...
[OK] Agent created: PPOAgentTF
   [RAND] Dirichlet Distribution: ENABLED
   [TOOL] Actor LR schedule: 0.000030@0 => 0.000020@150,000 => 0.000010@350,000
   [TOOL] Critic LR schedule: 0.000150@0 => 0.000120@150,000 => 0.000100@350,000
   State dim: 447
   Action dim: 10
   Actor LR (configured): 3e-05
   Actor LR (active): 0.000030
   Critic LR (active): 0.000150
   🧱 TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Cross-Asset Mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DNA] State augmentation: enabled=False
   [DOWN] Distributional critic: enabled=True | num_quantiles=17
   🎛️ Dirichlet controls: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Dual-head consistency coef: 0.0
   PPO update: epochs=3, batch_size=252, target_kl=0.0000, entropy_coef=0.0030
   [DOWN] PPO gamma schedule: 0.9900@0 => 0.9950@150,000 => 0.9980@350,000
   [DOWN] PPO GAE-λ schedule: 0.9200@0 => 0.9500@150,000 => 0.9700@350,000
   🎯 Entropy coef schedule: 0.0030@0 => 0.0030@100,000 => 0.0025@250,000 => 0.0015@400,000
   🧪 Aux-return coef schedule: 0.3500@0 => 0.3000@150,000 => 0.2500@300,000
   🌡️ Temperature schedule: 1.0000@0 => 0.9000@150,000 => 0.8000@300,000
   📐 PPO rollout schedule: 1008@0 => 1512@150,000 => 2016@300,000
   🧺 PPO batch-size schedule: 252@0 => 336@150,000 => 504@300,000
📊 Training metrics will stream to /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/logs/Exp6_TCN_FUSION_Enhanced_TAPE_training_20260313_055213_episodes.csv
🧪 Step diagnostics will stream to /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/logs/Exp6_TCN_FUSION_Enhanced_TAPE_training_20260313_055213_step_diagnostics.csv

🎯 Starting THREE-COMPONENT TAPE v3 training (with curriculum)...
   Total timesteps: 500,000
   Timesteps per update: scheduled
      0+ steps: timesteps_per_update=1008
      150,000+ steps: timesteps_per_update=1512
      300,000+ steps: timesteps_per_update=2016
   Number of updates: 348
   PPO batch_size: scheduled
      0+ steps: batch_size=252
      150,000+ steps: batch_size=336
      300,000+ steps: batch_size=504
   PPO gamma schedule: 0.9900@0 => 0.9950@150,000 => 0.9980@350,000
   PPO GAE-λ schedule: 0.9200@0 => 0.9500@150,000 => 0.9700@350,000
   📚 Episode Length Curriculum:
      0+ steps: limit=756
      100,000+ steps: limit=1008
      250,000+ steps: limit=1500
      400,000+ steps: limit=full
      ↳ smooth ramp: enabled (overlap=10,000 steps)
   📚 Turnover Scalar Curriculum:
      0+ steps: scalar=0.25
      100,000+ steps: scalar=0.55
      200,000+ steps: scalar=0.75
      300,000+ steps: scalar=0.90
      400,000+ steps: scalar=1.00
   🎛️ Action Execution Beta Curriculum:
      0+ steps: beta=0.35
      100,000+ steps: beta=0.45
      200,000+ steps: beta=0.55
      350,000+ steps: beta=0.60
   🏆 Deterministic-validation checkpoints: disabled
   🧷 Legacy checkpoint routes: configurable
   [WARN] Checkpoint selector default: legacy high-watermark path
   💾 High-watermark checkpoints: enabled (Sharpe >= 0.70, MDD <= 25.0%, skip_on_det_validation=True)
   ⏹️ Training early-stop: enabled (warmup=100,000 steps, patience=25 updates, min_delta=0.010, hard_dd=45.0% x 8)
[RCPT] Active feature manifest saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/logs/Exp6_TCN_FUSION_Enhanced_TAPE_training_20260313_055213_active_feature_manifest.json
[RCPT] Training metadata saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/logs/Exp6_TCN_FUSION_Enhanced_TAPE_training_20260313_055213_metadata.json
[CYCLE] Update 1/348 | Step 1,008/500,000 | Episode 0 | Time: 66.0s
   📊 Metrics: Return=+3.68% | Sharpe=0.182 | DD=18.59% | Turnover=7.14%
   🎚️ Intra-Step TAPE: potential=0.5423 | delta_reward=+0.0013
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.2113 | critic_loss=0.3379 | mean_adv=-0.0000
   🧮 Loss Detail: critic_scaled=0.1690 | risk_aux_total=0.0000 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0000 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0011 | dispersion_loss=0.0016
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=0.1822 | ema=0.1822 | best_ema=0.1822 | no_improve=0
[CYCLE] Update 2/348 | Step 2,016/500,000 | Episode 0 | Time: 117.6s
   📊 Metrics: Return=+34.55% | Sharpe=0.667 | DD=26.81% | Turnover=7.69%
   🎚️ Intra-Step TAPE: potential=0.7293 | delta_reward=-0.0000
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.1642 | critic_loss=0.2714 | mean_adv=-0.0000
   🧮 Loss Detail: critic_scaled=0.1357 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0011 | dispersion_loss=0.0012
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=0.6233 | ema=0.2263 | best_ema=0.2263 | no_improve=0
   🔬 Alpha Diversity: mean=8.76 | std=3.10 | range=[0.33, 16.00] | cap_hit=1.4%
   🏷️ Alpha Per-Asset  TOP: NVDA=12.16 | CAT=9.95 | AMZN=9.69  BOT: JNJ=9.04 | JPM=9.04 | XOM=7.94
   🧭 Regime Start Dist (train resets): high_vol=1 (25.0%), low_vol=2 (50.0%), medium_vol=1 (25.0%)
   🔐 Lagrangian CVaR: λ=0.0019 | penalty=-0.0000 | rolling_cvar=-0.02272
      💾 Sharpe-threshold checkpoint saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00002_shp1p153_actor.weights.h5 (Sharpe=1.153, MDD=18.77%)
      💾 Sharpe-threshold checkpoint saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00004_shp1p259_actor.weights.h5 (Sharpe=1.259, MDD=18.12%)
[CYCLE] Update 3/348 | Step 3,024/500,000 | Episode 4 | Time: 169.7s
   📊 Metrics: Return=+69.17% | Sharpe=1.259 | DD=18.12% | Turnover=8.39%
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.1313 | critic_loss=0.1413 | mean_adv=0.0000
   🧮 Loss Detail: critic_scaled=0.0707 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0012 | dispersion_loss=0.0010
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=1.2589 | ema=0.3295 | best_ema=0.3295 | no_improve=0
   🔒 Drawdown λ snapshot=0.000 (peak 0.000, dd 0.00% / trig 16.50%) | terminal=0.000 (peak 0.500) | TAPE=0.5360
   📈 Outperformance: 1/N bonus=0.000 (EW ret=-0.00013) | SPY bonus=0.000 (SPY ret=-0.00025)
   🔐 Lagrangian CVaR: λ=0.0121 | penalty=-0.0001 | rolling_cvar=-0.02152
[CYCLE] Update 4/348 | Step 4,032/500,000 | Episode 4 | Time: 222.4s
   📊 Metrics: Return=-0.88% | Sharpe=-0.088 | DD=20.22% | Turnover=12.27%
   🎚️ Intra-Step TAPE: potential=0.7543 | delta_reward=+0.0000
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.1133 | critic_loss=0.2121 | mean_adv=0.0000
   🧮 Loss Detail: critic_scaled=0.1060 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0012 | dispersion_loss=0.0008
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=-0.0877 | ema=0.2878 | best_ema=0.2878 | no_improve=0
   🔬 Alpha Diversity: mean=3.48 | std=1.21 | range=[1.05, 8.06] | cap_hit=0.0%
   🏷️ Alpha Per-Asset  TOP: NVDA=5.27 | GLD=4.24 | NEE=3.92  BOT: JPM=3.22 | XOM=3.17 | MSFT=3.03
   🧭 Regime Start Dist (train resets): high_vol=3 (37.5%), low_vol=4 (50.0%), medium_vol=1 (12.5%)
[CYCLE] Update 5/348 | Step 5,040/500,000 | Episode 4 | Time: 276.2s
   📊 Metrics: Return=-11.06% | Sharpe=-0.311 | DD=25.52% | Turnover=15.00%
   🎚️ Intra-Step TAPE: potential=0.2122 | delta_reward=-0.0000
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.0974 | critic_loss=0.2574 | mean_adv=-0.0000
   🧮 Loss Detail: critic_scaled=0.1287 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0013 | dispersion_loss=0.0009
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=-0.3231 | ema=0.2267 | best_ema=0.2267 | no_improve=0
      💾 Sharpe-threshold checkpoint saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00007_shp0p769_actor.weights.h5 (Sharpe=0.769, MDD=23.66%)
      💾 Sharpe-threshold checkpoint saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00008_shp1p444_actor.weights.h5 (Sharpe=1.444, MDD=14.67%)
[CYCLE] Update 6/348 | Step 6,048/500,000 | Episode 8 | Time: 330.7s
   📊 Metrics: Return=+74.86% | Sharpe=1.444 | DD=14.67% | Turnover=17.54%
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.0938 | critic_loss=0.2238 | mean_adv=-0.0000
   🧮 Loss Detail: critic_scaled=0.1119 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0014 | dispersion_loss=0.0006
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=1.4440 | ema=0.3485 | best_ema=0.3485 | no_improve=0
   🔬 Alpha Diversity: mean=0.91 | std=0.54 | range=[0.46, 3.61] | cap_hit=0.0%
   🏷️ Alpha Per-Asset  TOP: GLD=1.03 | NEE=0.88 | JNJ=0.79  BOT: AMZN=0.70 | MSFT=0.68 | JPM=0.65
   🧭 Regime Start Dist (train resets): high_vol=5 (41.7%), low_vol=4 (33.3%), medium_vol=3 (25.0%)
   🔒 Drawdown λ snapshot=0.000 (peak 0.000, dd 0.00% / trig 16.50%) | terminal=0.000 (peak 0.000) | TAPE=0.5823
   📈 Outperformance: 1/N bonus=0.000 (EW ret=-0.00054) | SPY bonus=0.006 (SPY ret=-0.00200)
   🔐 Lagrangian CVaR: λ=0.0027 | penalty=-0.0000 | rolling_cvar=-0.01851
[CYCLE] Update 7/348 | Step 7,056/500,000 | Episode 8 | Time: 384.6s
   📊 Metrics: Return=+5.24% | Sharpe=0.368 | DD=10.15% | Turnover=23.87%
   🎚️ Intra-Step TAPE: potential=0.7169 | delta_reward=-0.0002
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.0898 | critic_loss=0.1003 | mean_adv=-0.0000
   🧮 Loss Detail: critic_scaled=0.0502 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0014 | dispersion_loss=0.0005
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=0.3678 | ema=0.3504 | best_ema=0.3504 | no_improve=0
[CYCLE] Update 8/348 | Step 8,064/500,000 | Episode 8 | Time: 438.1s
   📊 Metrics: Return=+24.82% | Sharpe=0.586 | DD=21.38% | Turnover=24.26%
   🎚️ Intra-Step TAPE: potential=0.2308 | delta_reward=-0.0000
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.0851 | critic_loss=0.2047 | mean_adv=0.0000
   🧮 Loss Detail: critic_scaled=0.1023 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0013 | dispersion_loss=0.0007
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=0.5864 | ema=0.3740 | best_ema=0.3740 | no_improve=0
   🔬 Alpha Diversity: mean=1.09 | std=0.54 | range=[0.53, 3.50] | cap_hit=0.0%
   🏷️ Alpha Per-Asset  TOP: GLD=1.21 | NEE=1.04 | XOM=1.00  BOT: NVDA=0.82 | MSFT=0.80 | AMZN=0.77
   🧭 Regime Start Dist (train resets): high_vol=5 (41.7%), low_vol=4 (33.3%), medium_vol=3 (25.0%)
   🔐 Lagrangian CVaR: λ=0.0000 | penalty=-0.0000 | rolling_cvar=-0.01310
      💾 Sharpe-threshold checkpoint saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00009_shp0p740_actor.weights.h5 (Sharpe=0.740, MDD=21.38%)
[CYCLE] Update 9/348 | Step 9,072/500,000 | Episode 12 | Time: 490.6s
   📊 Metrics: Return=+19.34% | Sharpe=0.432 | DD=16.50% | Turnover=24.31%
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.0843 | critic_loss=0.1424 | mean_adv=0.0000
   🧮 Loss Detail: critic_scaled=0.0712 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0013 | dispersion_loss=0.0008
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=0.4322 | ema=0.3798 | best_ema=0.3798 | no_improve=0
   🔒 Drawdown λ snapshot=0.000 (peak 0.000, dd 0.00% / trig 16.50%) | terminal=0.000 (peak 0.000) | TAPE=0.2741
   📈 Outperformance: 1/N bonus=0.000 (EW ret=-0.02418) | SPY bonus=0.042 (SPY ret=-0.03007)
   🔐 Lagrangian CVaR: λ=0.0000 | penalty=-0.0000 | rolling_cvar=-0.01751
[CYCLE] Update 10/348 | Step 10,080/500,000 | Episode 12 | Time: 544.7s
   📊 Metrics: Return=+1.00% | Sharpe=-0.008 | DD=12.75% | Turnover=24.73%
   🎚️ Intra-Step TAPE: potential=0.2330 | delta_reward=+0.0000
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.0788 | critic_loss=0.0927 | mean_adv=0.0000
   🧮 Loss Detail: critic_scaled=0.0464 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0012 | dispersion_loss=0.0009
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=-0.0083 | ema=0.3410 | best_ema=0.3410 | no_improve=0
   🔬 Alpha Diversity: mean=0.99 | std=0.25 | range=[0.59, 2.14] | cap_hit=0.0%
   🏷️ Alpha Per-Asset  TOP: GLD=1.10 | NEE=0.99 | XOM=0.97  BOT: JPM=0.85 | MSFT=0.84 | AMZN=0.80
   🧭 Regime Start Dist (train resets): high_vol=5 (31.2%), low_vol=5 (31.2%), medium_vol=6 (37.5%)
[CYCLE] Update 11/348 | Step 11,088/500,000 | Episode 12 | Time: 598.1s
   📊 Metrics: Return=+25.15% | Sharpe=0.538 | DD=25.85% | Turnover=24.78%
   🎚️ Intra-Step TAPE: potential=0.6393 | delta_reward=+0.0004
   🎯 Profile: BalancedGrowth
   [BRAIN] Training: actor_loss=0.0756 | critic_loss=0.1424 | mean_adv=-0.0000
   🧮 Loss Detail: critic_scaled=0.0712 | risk_aux_total=0.0001 | sharpe_proxy=0.0000 | sharpe_loss=0.0000 | mvo_loss=0.0001 | cvar_proxy=0.0000 | cvar_loss=0.0000 | cvar_coef=0.0000 | hhi_loss=0.0012 | dispersion_loss=0.0010
   ⚙️ Optimizer: actor_lr=0.000030 | critic_lr=0.000150 | target_kl=0.0000 | rollout=1008 | batch_size=252 | gamma=0.9900 | gae_lambda=0.9200
   ⏹️ Early-stop monitor: score=0.5177 | ema=0.3587 | best_ema=0.3587 | no_improve=0
   🔐 Lagrangian CVaR: λ=0.0000 | penalty=-0.0000 | rolling_cvar=-0.02180
      💾 Sharpe-threshold checkpoint saved: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00015_shp0p747_actor.weights.h5 (Sharpe=0.747, MDD=20.20%)

## 5) Inspect Latest Training Logs
Load the latest training CSVs and inspect the current run.

In [6]:
TRAIN_RESULTS_ROOT = TRAIN_REPO_DIR / 'tcn_fusion_results'
TRAIN_LOGS_DIR = TRAIN_RESULTS_ROOT / 'logs'

episodes_files = sorted(TRAIN_LOGS_DIR.glob('*episodes*.csv'), key=lambda p: p.stat().st_mtime, reverse=True)
if not episodes_files:
    print(f'No episodes CSV found in {TRAIN_LOGS_DIR}')
else:
    train_episodes_path = episodes_files[0]
    train_episodes_df = pd.read_csv(train_episodes_path)
    print('Episodes file:', train_episodes_path)
    print('Rows:', len(train_episodes_df))
    display(train_episodes_df.tail(20))

step_diag_files = sorted(TRAIN_LOGS_DIR.glob('*step_diagnostics*.csv'), key=lambda p: p.stat().st_mtime, reverse=True)
if step_diag_files:
    step_diag_path = step_diag_files[0]
    step_diag_df = pd.read_csv(step_diag_path)
    print('Step diagnostics file:', step_diag_path)
    print('Rows:', len(step_diag_df))
    display(step_diag_df.tail(20))

Episodes file: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/logs/Exp6_TCN_FUSION_Enhanced_TAPE_training_20260313_055213_episodes.csv
Rows: 119

,update,timestep,episode,elapsed_time,episode_return_pct,episode_sharpe,episode_sortino,episode_max_dd,episode_volatility,episode_win_rate,...,explained_variance,actor_grad_norm,critic_grad_norm,alpha_min,alpha_max,alpha_mean,alpha_cap_hit_frac,ratio_mean,ratio_std,drawdown_lambda_peak
99,100,100800,128,5347.103928,59.507136,0.684383,0.781472,27.818635,0.188351,57.063404,...,0.939536,1.423367,0.323341,0.776118,2.116785,1.311142,0.0,0.929703,2.451816,0.027147
100,101,101808,130,5400.609791,69.401530,0.732294,0.894310,24.383358,0.183598,55.325750,...,0.927997,1.254053,0.349891,0.832329,2.162570,1.238821,0.0,1.057877,3.591024,0.036090
101,102,102816,132,5453.971004,73.296632,0.737701,0.836185,27.227249,0.182370,56.405164,...,0.913525,1.326332,0.414890,0.925264,1.921234,1.282567,0.0,1.074485,3.606202,0.080436
102,103,103824,132,5507.913365,57.445277,1.534500,2.028997,8.832721,0.106000,56.877898,...,0.918279,1.668184,0.497788,0.918076,1.790337,1.192616,0.0,1.074857,3.461167,0.080436
103,104,104832,132,5561.761507,50.759485,0.839062,1.073296,18.784261,0.122512,56.284761,...,0.932671,1.361065,0.879080,0.887774,1.818504,1.116009,0.0,1.053783,3.106730,0.080436
104,105,105840,134,5616.409622,43.378985,0.509729,0.579168,27.261356,0.164765,55.412115,...,0.932354,1.104703,0.231742,0.733132,1.730751,0.967926,0.0,1.015504,2.736145,0.059222
105,106,106848,136,5671.609739,63.182356,0.656313,0.748759,27.422990,0.181868,56.504469,...,0.927724,1.168565,0.164439,0.645466,2.038047,0.912607,0.0,0.925464,1.959766,0.091534
106,107,107856,136,5725.980523,18.562089,0.331409,0.403097,22.585116,0.201626,54.404946,...,0.940771,1.357265,0.425095,0.589667,2.097779,0.865554,0.0,1.055430,2.688126,0.091534
107,108,108864,136,5779.475253,47.233451,0.575412,0.696836,22.585116,0.183237,56.173526,...,0.945698,1.408439,0.407277,0.731949,2.000364,0.969604,0.0,0.951545,2.013271,0.091534
108,109,109872,138,5833.502748,67.745874,0.701795,0.823028,25.576983,0.179177,56.504469,...,0.939203,1.502077,0.468812,0.847958,2.212161,1.097595,0.0,0.996500,2.470634,0.044417
109,110,110880,140,5887.323788,54.639474,0.611706,0.722159,23.985176,0.169538,56.206554,...,0.928445,1.011422,0.426357,0.817882,2.124568,1.097885,0.0,0.965499,2.318393,0.038520
110,111,111888,140,5941.359273,51.996871,1.461845,1.921188,7.981081,0.101573,57.187017,...,0.914042,1.338683,0.356049,0.802684,2.457161,1.024248,0.0,0.915370,2.176477,0.038520
111,112,112896,140,5995.097799,47.774660,0.836369,1.084714,18.053349,0.115167,55.617353,...,0.920443,1.432996,0.513561,0.835940,3.073213,1.105116,0.0,0.996626,3.020782,0.038520
112,113,113904,142,6049.242918,48.085728,0.569421,0.643596,26.502094,0.160508,55.610725,...,0.888601,1.244824,0.163528,0.853249,2.423516,1.091084,0.0,1.115023,4.324069,0.066370
113,114,114912,144,6102.044705,49.617170,0.566606,0.652513,23.563138,0.168024,56.504469,...,0.942419,1.415401,0.243858,0.869636,2.343328,1.125751,0.0,0.984148,2.235405,0.031709
114,115,115920,144,6154.708619,27.795015,0.691400,0.858698,16.107089,0.119956,55.950541,...,0.919752,1.273960,0.213114,0.858411,2.286677,1.180864,0.0,1.019696,2.696682,0.031709
115,116,116928,144,6207.793864,52.757383,0.657266,0.746522,26.338519,0.173588,56.618465,...,0.947044,1.307718,0.301589,0.798028,2.128727,1.411019,0.0,1.032103,3.013464,0.031709
116,117,117936,146,6261.095124,50.020869,0.564735,0.663579,26.737955,0.170412,55.610725,...,0.902680,1.084476,0.379442,0.818263,2.369546,1.796965,0.0,1.113599,4.726460,0.056513
117,118,118944,148,6314.487214,74.812946,1.084358,1.385355,19.472617,0.116983,56.802383,...,0.916305,0.911770,0.229926,1.322900,2.699051,1.856905,0.0,1.075785,4.734474,0.003624
118,119,119952,148,6367.739032,68.647467,1.863099,2.539124,8.007597,0.101436,55.486862,...,0.911881,1.106346,0.368497,1.285766,2.395498,1.839488,0.0,1.093504,4.976167,0.003624

Step diagnostics file: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/logs/Exp6_TCN_FUSION_Enhanced_TAPE_training_20260313_055213_step_diagnostics.csv
Rows: 119952

,update,timestep,episode,episode_step,date,elapsed_time,reward_total,portfolio_return_pct_points,portfolio_value,prev_portfolio_value,...,turnover_penalty_contrib,transaction_cost_dollars,tx_cost_contrib_reward_pts,action_realization_l1,action_realization_penalty,cash_weight_raw,cash_weight_projected,cash_weight_final,cash_weight_forced_gap,drawdown_penalty
119932,119,119933,148,643,2018-09-14 00:00:00,6354.920041,-0.077329,0.041743,168233.814848,168163.618907,...,-0.066536,66.030993,-0.039266,0.090183,0.045091,0.022944,0.050000,0.076315,0.027056,0.0
119933,119,119934,148,496,2018-08-09 00:00:00,6354.922971,0.545454,-0.327850,138375.933203,138831.091094,...,0.000000,40.113488,-0.028894,0.000000,0.000000,0.072594,0.072594,0.077600,0.000000,0.0
119934,119,119935,148,565,2019-03-04 00:00:00,6354.925943,0.095913,0.237845,128680.234124,128374.901208,...,0.000000,31.995178,-0.024923,0.059009,0.029505,0.020495,0.050000,0.096189,0.029505,0.0
119935,119,119936,148,462,2018-01-29 00:00:00,6354.928734,-0.374158,-0.342455,155946.247473,156482.128441,...,0.000000,29.303703,-0.018727,0.028417,0.014209,0.035791,0.050000,0.063358,0.014209,0.0
119936,119,119937,148,644,2018-09-17 00:00:00,6355.080742,0.272965,-0.123863,168025.436092,168233.814848,...,0.000000,51.804627,-0.030793,0.219402,0.109701,0.013885,0.050000,0.064473,0.036115,0.0
119937,119,119938,148,497,2018-08-10 00:00:00,6355.083873,-0.691687,-0.474743,137719.002724,138375.933203,...,0.000000,39.103655,-0.028259,0.083374,0.041687,0.084167,0.084167,0.080555,0.000000,0.0
119938,119,119939,148,566,2019-03-05 00:00:00,6355.086916,0.927953,-0.193915,128430.703489,128680.234124,...,0.000000,32.672980,-0.025391,0.020030,0.010015,0.039985,0.050000,0.075404,0.010015,0.0
119939,119,119940,148,463,2018-01-30 00:00:00,6355.089729,-0.711819,-0.487958,155185.294805,155946.247473,...,0.000000,39.235384,-0.025160,0.000000,0.000000,0.064383,0.064383,0.063819,0.000000,0.0
119940,119,119941,148,645,2018-09-18 00:00:00,6355.240436,0.120822,0.043013,168097.709012,168025.436092,...,0.000000,25.912232,-0.015422,0.042940,0.021470,0.028530,0.050000,0.057960,0.021470,0.0
119941,119,119942,148,498,2018-08-13 00:00:00,6355.243268,-0.496929,-0.422479,137137.168705,137719.002724,...,0.000000,33.253972,-0.024146,0.059217,0.029608,0.020392,0.050000,0.066805,0.029608,0.0
119942,119,119943,148,567,2019-03-06 00:00:00,6355.246049,-0.885834,-0.791632,127414.005414,128430.703489,...,0.000000,27.877008,-0.021706,0.016557,0.008279,0.041721,0.050000,0.063972,0.008279,0.0
119943,119,119944,148,464,2018-01-31 00:00:00,6355.248838,1.102517,0.461422,155901.354472,155185.294805,...,0.000000,45.589833,-0.029378,0.201761,0.100880,0.054340,0.054340,0.059554,0.000000,0.0
119944,119,119945,148,646,2018-09-19 00:00:00,6355.402890,1.119851,-0.121282,167893.836468,168097.709012,...,0.000000,41.441055,-0.024653,0.145429,0.072714,0.031775,0.050000,0.054378,0.018225,0.0
119945,119,119946,148,499,2018-08-14 00:00:00,6355.405950,0.983297,0.381698,137660.618761,137137.168705,...,0.000000,23.660706,-0.017253,0.000000,0.000000,0.158604,0.158604,0.108115,0.000000,0.0
119946,119,119947,148,568,2019-03-07 00:00:00,6355.408771,-0.200083,-0.739266,126472.077196,127414.005414,...,0.000000,38.106696,-0.029908,0.000000,0.000000,0.084389,0.084389,0.073159,0.000000,0.0
119947,119,119948,148,465,2018-02-01 00:00:00,6355.411499,-1.304064,-0.760229,154716.146616,155901.354472,...,0.000000,44.477019,-0.028529,0.158826,0.079413,0.122065,0.122065,0.087684,0.000000,0.0
119948,119,119949,148,647,2018-09-20 00:00:00,6355.563897,0.588562,0.448873,168647.466992,167893.836468,...,0.000000,36.267029,-0.021601,0.000000,0.000000,0.071237,0.071237,0.061965,0.000000,0.0
119949,119,119950,148,500,2018-08-15 00:00:00,6355.566943,-0.988419,-0.532497,136927.579586,137660.618761,...,0.000000,40.935306,-0.029736,0.250581,0.125290,0.069016,0.069016,0.090520,0.000000,0.0
119950,119,119951,148,569,2019-03-08 00:00:00,6355.569793,-0.279080,-0.221698,126191.690636,126472.077196,...,0.000000,32.789721,-0.025926,0.000000,0.000000,0.111908,0.111908,0.090596,0.000000,0.0
119951,119,119952,148,466,2018-02-02 00:00:00,6355.572492,-2.394879,-1.606842,152230.103277,154716.146616,...,0.000000,25.733551,-0.016633,0.012450,0.006225,0.043775,0.050000,0.070726,0.006225,0.0

## 6) Export Artifacts (Optional)
Zip the latest results and optionally copy them to Google Drive.

In [8]:
import subprocess

EXPORT_RESULTS_ZIP = True
COPY_TO_DRIVE = True
EXPORT_PATH = Path(f'/content/tcn_tape_vectorized_{RUN_ID}.zip')

if EXPORT_RESULTS_ZIP:
    include_paths = [
        TRAIN_REPO_DIR / 'tcn_fusion_results',
        TRAIN_REPO_DIR / 'data' / 'phase1_preparation_artifacts',
        TRAIN_REPO_DIR / 'data' / 'master_features_NORMALIZED.csv',
        TRAIN_REPO_DIR / 'data_exports',
        TRAIN_REPO_DIR / 'output_log',
        TRAIN_REPO_DIR / 'output_logs',
    ]
    existing = []
    seen = set()
    for path in include_paths:
        resolved = path.resolve()
        if resolved.exists() and resolved not in seen:
            seen.add(resolved)
            existing.append(resolved)

    if existing:
        if EXPORT_PATH.exists():
            EXPORT_PATH.unlink()
        relative_items = [str(path.relative_to(TRAIN_REPO_DIR)) for path in existing]
        subprocess.run(
            ['bash', '-lc', 'cd "{}" && zip -qr "{}" {}'.format(TRAIN_REPO_DIR, EXPORT_PATH, ' '.join(f'"{item}"' for item in relative_items))],
            check=True,
        )
        print('[OK] Created:', EXPORT_PATH)

        if COPY_TO_DRIVE:
            from google.colab import drive
            drive.mount('/content/drive')
            subprocess.run(['cp', str(EXPORT_PATH), '/content/drive/MyDrive/'], check=True)
            print('[OK] Copied to Drive:', f'/content/drive/MyDrive/{EXPORT_PATH.name}')
    else:
        print('[WARN] Nothing to export.')
else:
    print('[SKIP] EXPORT_RESULTS_ZIP=False')

Mounted at /content/drive
[OK] Copied to Drive: /content/drive/MyDrive/tcn_tape_vectorized_run10.zip

In [9]:
from pathlib import Path
import csv, re

root = Path("/content/tcn_tape_vectorized_version_clean/tcn_fusion_results")
log_dir = root / "logs"
ckpt_dir = root / "high_watermark_checkpoints"

# latest episodes csv
ep_csv = sorted(log_dir.glob("*_episodes.csv"), key=lambda p: p.stat().st_mtime)[-1]
print("episodes_csv:", ep_csv)

rows = list(csv.DictReader(ep_csv.open()))
print("rows:", len(rows))
if rows:
    last = rows[-1]
    for k in ["update", "step", "episode", "episode_sharpe", "episode_return_pct", "episode_turnover_pct"]:
        if k in last:
            print(k, "=", last[k])

# best checkpoint by Sharpe tag in filename
pat = re.compile(r"shp([pm]?\d+p\d+)")
best = None
for f in ckpt_dir.glob("*_actor.weights.h5"):
    m = pat.search(f.name)
    if not m:
        continue
    t = m.group(1)
    sign = -1 if t.startswith("m") else 1
    t = t[1:] if t[0] in "pm" else t
    sh = sign * float(t.replace("p", "."))
    if best is None or sh > best[0]:
        best = (sh, f)

print("best_checkpoint:", best[1] if best else None)
print("best_sharpe_tag:", best[0] if best else None)

episodes_csv: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/logs/Exp6_TCN_FUSION_Enhanced_TAPE_training_20260313_055213_episodes.csv
rows: 119
update = 119
episode = 148
episode_sharpe = 1.8630986757129058
episode_return_pct = 68.64746699151563
episode_turnover_pct = 26.506832242012024
best_checkpoint: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00008_shp1p444_actor.weights.h5
best_sharpe_tag: 1.444

In [ ]:
# Rank all saved checkpoints by deterministic eval Sharpe, then run stochastic on top-K

from pathlib import Path
import copy
import pandas as pd
import numpy as np

# ---- knobs ----
RESULTS_ROOT = Path("/content/tcn_tape_vectorized_version_clean/tcn_fusion_results")
HORIZON_DAYS = 756          # change to 252/504/756/1008
DET_SEED = 6042
TOP_K = 3
STOCH_RUNS_TOPK = 20        # set 0 to skip stochastic pass

# ---- resolve objects from notebook globals ----
exp_obj = globals().get("train_experiment6") or globals().get("experiment6")
phase1_obj = globals().get("eval_phase1_data") or globals().get("train_phase1_data")
base_cfg = globals().get("eval_config") or globals().get("train_config")

if exp_obj is None or phase1_obj is None or base_cfg is None:
    raise RuntimeError("Missing one of: experiment6/train_experiment6, eval_phase1_data/train_phase1_data, eval_config/train_config")

# if helper not in scope yet
if "evaluate_experiment6_checkpoint" not in globals():
    from src.notebook_helpers.tcn_phase1 import evaluate_experiment6_checkpoint

cfg = copy.deepcopy(base_cfg)

# ---- discover checkpoint prefixes ----
prefixes = []
for actor_path in (RESULTS_ROOT / "high_watermark_checkpoints").glob("*_actor.weights.h5"):
    prefix = str(actor_path).replace("_actor.weights.h5", "")
    critic_path = Path(prefix + "_critic.weights.h5")
    if critic_path.exists():
        prefixes.append(prefix)

prefixes = sorted(set(prefixes))
print(f"Found {len(prefixes)} candidate checkpoints")

# ---- deterministic ranking ----
det_rows = []
for i, prefix in enumerate(prefixes, 1):
    try:
        er = evaluate_experiment6_checkpoint(
            experiment6=exp_obj,
            phase1_data=phase1_obj,
            config=cfg,
            random_seed=DET_SEED,
            checkpoint_path_override=prefix,
            deterministic_eval_mode="mean",
            stochastic_eval_mode="sample",
            num_eval_runs=0,
            stochastic_episode_length_limit=HORIZON_DAYS,
            save_eval_logs=False,
            save_eval_artifacts=False,
        )
        dm = er.deterministic_metrics or {}
        det_rows.append({
            "prefix": prefix,
            "det_sharpe": float(dm.get("sharpe_ratio", np.nan)),
            "det_return_pct": float(dm.get("total_return_pct", np.nan)),
            "det_mdd_pct": float(dm.get("max_drawdown_pct", np.nan)),
            "det_turnover_pct": float(dm.get("turnover", np.nan)) * 100.0 if dm.get("turnover", None) is not None else np.nan,
        })
    except Exception as e:
        det_rows.append({"prefix": prefix, "error": f"{type(e).__name__}: {e}"})

det_df = pd.DataFrame(det_rows)
ok_df = det_df[det_df["det_sharpe"].notna()].copy()
ranked_df = ok_df.sort_values(["det_sharpe", "det_return_pct", "det_mdd_pct"], ascending=[False, False, True]).reset_index(drop=True)

print("\nTop deterministic checkpoints")
display(ranked_df.head(TOP_K))

# ---- stochastic pass on top-K ----
if STOCH_RUNS_TOPK > 0 and not ranked_df.empty:
    st_rows = []
    for _, r in ranked_df.head(TOP_K).iterrows():
        prefix = r["prefix"]
        er = evaluate_experiment6_checkpoint(
            experiment6=exp_obj,
            phase1_data=phase1_obj,
            config=cfg,
            random_seed=DET_SEED + 100000,
            checkpoint_path_override=prefix,
            deterministic_eval_mode="mean",
            stochastic_eval_mode="sample",
            num_eval_runs=STOCH_RUNS_TOPK,
            stochastic_episode_length_limit=HORIZON_DAYS,
            save_eval_logs=False,
            save_eval_artifacts=False,
        )
        sto = er.stochastic_results if isinstance(er.stochastic_results, pd.DataFrame) else pd.DataFrame()
        st_rows.append({
            "prefix": prefix,
            "det_sharpe": r["det_sharpe"],
            "sto_sharpe_mean": float(sto["sharpe_ratio"].mean()) if "sharpe_ratio" in sto else np.nan,
            "sto_sharpe_std": float(sto["sharpe_ratio"].std()) if "sharpe_ratio" in sto else np.nan,
            "sto_return_mean_pct": float(sto["total_return"].mean() * 100.0) if "total_return" in sto else np.nan,
            "sto_mdd_mean_pct": float(sto["max_drawdown"].mean() * 100.0) if "max_drawdown" in sto else np.nan,
        })

    st_df = pd.DataFrame(st_rows).sort_values(["sto_sharpe_mean", "det_sharpe"], ascending=[False, False]).reset_index(drop=True)
    print("\nTop-K stochastic rerank")
    display(st_df)

Found 60 candidate checkpoints

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00002_shp1p153
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00002_shp1p153_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00002_shp1p153_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $193,016.65
   Total Return: +93.02%
   Annualized Return: +19.78%
   Sharpe Ratio: 1.0446 (annualized)
   Sortino Ratio: 1.4934 (annualized)
   Max Drawdown: 19.96%
   Volatility (Ann.): 16.75%
   Turnover: 0.73%
   Win Rate: 54.53%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.091, argmax_alpha_uniques=8

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 0 Runs)
================================================================================

[IDEA] Skipped stochastic evaluation (num_eval_runs=0)

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00004_shp1p259
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00004_shp1p259_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00004_shp1p259_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $193,016.65
   Total Return: +93.02%
   Annualized Return: +19.78%
   Sharpe Ratio: 1.0446 (annualized)
   Sortino Ratio: 1.4934 (annualized)
   Max Drawdown: 19.96%
   Volatility (Ann.): 16.75%
   Turnover: 0.73%
   Win Rate: 54.53%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.091, argmax_alpha_uniques=8

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 0 Runs)
================================================================================

[IDEA] Skipped stochastic evaluation (num_eval_runs=0)

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00007_shp0p769
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00007_shp0p769_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00007_shp0p769_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $165,722.96
   Total Return: +65.72%
   Annualized Return: +14.87%
   Sharpe Ratio: 0.9524 (annualized)
   Sortino Ratio: 1.3437 (annualized)
   Max Drawdown: 16.79%
   Volatility (Ann.): 13.45%
   Turnover: 0.71%
   Win Rate: 54.31%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.702, argmax_alpha_uniques=3

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 0 Runs)
================================================================================

[IDEA] Skipped stochastic evaluation (num_eval_runs=0)

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00008_shp1p444
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00008_shp1p444_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00008_shp1p444_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $165,722.96
   Total Return: +65.72%
   Annualized Return: +14.87%
   Sharpe Ratio: 0.9524 (annualized)
   Sortino Ratio: 1.3437 (annualized)
   Max Drawdown: 16.79%
   Volatility (Ann.): 13.45%
   Turnover: 0.71%
   Win Rate: 54.31%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.702, argmax_alpha_uniques=3

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 0 Runs)
================================================================================

[IDEA] Skipped stochastic evaluation (num_eval_runs=0)

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00009_shp0p740
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00009_shp0p740_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00009_shp0p740_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $161,726.66
   Total Return: +61.73%
   Annualized Return: +14.11%
   Sharpe Ratio: 0.9171 (annualized)
   Sortino Ratio: 1.2746 (annualized)
   Max Drawdown: 16.86%
   Volatility (Ann.): 13.20%
   Turnover: 0.66%
   Win Rate: 54.31%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.806, argmax_alpha_uniques=1

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 0 Runs)
================================================================================

[IDEA] Skipped stochastic evaluation (num_eval_runs=0)

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00015_shp0p747
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00015_shp0p747_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00015_shp0p747_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $170,956.31
   Total Return: +70.96%
   Annualized Return: +15.86%
   Sharpe Ratio: 0.9627 (annualized)
   Sortino Ratio: 1.3543 (annualized)
   Max Drawdown: 18.11%
   Volatility (Ann.): 14.32%
   Turnover: 0.62%
   Win Rate: 54.09%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.939, argmax_alpha_uniques=4

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 0 Runs)
================================================================================

[IDEA] Skipped stochastic evaluation (num_eval_runs=0)

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00019_shp0p720
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00019_shp0p720_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00019_shp0p720_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True

,prefix,det_sharpe,det_return_pct,det_mdd_pct,det_turnover_pct
0,/content/tcn_tape_vectorized_version_clean/tcn...,1.044581,NaN,NaN,0.726482
1,/content/tcn_tape_vectorized_version_clean/tcn...,1.044581,NaN,NaN,0.726482
2,/content/tcn_tape_vectorized_version_clean/tcn...,1.008787,NaN,NaN,0.384217

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00002_shp1p153
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00002_shp1p153_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00002_shp1p153_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $193,016.65
   Total Return: +93.02%
   Annualized Return: +19.78%
   Sharpe Ratio: 1.0446 (annualized)
   Sortino Ratio: 1.4934 (annualized)
   Max Drawdown: 19.96%
   Volatility (Ann.): 16.75%
   Turnover: 0.73%
   Win Rate: 54.53%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.091, argmax_alpha_uniques=8

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 20 Runs)
================================================================================

[RAND] Run 1/20 (Seed=106142):
   Start Date: 2022-08-23 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +50.76%
   Annualized Return: +14.66%
   Sharpe: 0.8105
   Volatility (Ann.): 16.05%
   Max DD: 20.37%
   Turnover (episode): 39.74%
   Turnover (step): mean=39.740% | p95=56.404% | max=78.741%
   Turnover vs target: target=35.000% | exceed_rate=65.6% | mean_excess=6.598%
   Raw/Executed turnover: raw_mean=39.740% | executed/raw=1.000

[RAND] Run 2/20 (Seed=106143):
   Start Date: 2022-04-29 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +31.08%
   Annualized Return: +9.44%
   Sharpe: 0.4936
   Volatility (Ann.): 17.33%
   Max DD: 18.89%
   Turnover (episode): 40.77%
   Turnover (step): mean=40.771% | p95=58.309% | max=77.091%
   Turnover vs target: target=35.000% | exceed_rate=69.3% | mean_excess=7.634%
   Raw/Executed turnover: raw_mean=40.771% | executed/raw=1.000

[RAND] Run 3/20 (Seed=106144):
   Start Date: 2022-04-14 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +16.92%
   Annualized Return: +5.35%
   Sharpe: 0.2714
   Volatility (Ann.): 17.67%
   Max DD: 21.77%
   Turnover (episode): 40.32%
   Turnover (step): mean=40.316% | p95=55.909% | max=79.489%
   Turnover vs target: target=35.000% | exceed_rate=67.7% | mean_excess=7.140%
   Raw/Executed turnover: raw_mean=40.316% | executed/raw=1.000

[RAND] Run 4/20 (Seed=106145):
   Start Date: 2022-03-30 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +21.00%
   Annualized Return: +6.56%
   Sharpe: 0.3474
   Volatility (Ann.): 16.55%
   Max DD: 25.20%
   Turnover (episode): 40.70%
   Turnover (step): mean=40.704% | p95=59.088% | max=73.420%
   Turnover vs target: target=35.000% | exceed_rate=68.6% | mean_excess=7.490%
   Raw/Executed turnover: raw_mean=40.704% | executed/raw=1.000

[RAND] Run 5/20 (Seed=106146):
   Start Date: 2022-06-21 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +59.15%
   Annualized Return: +16.75%
   Sharpe: 0.9092
   Volatility (Ann.): 16.35%
   Max DD: 19.13%
   Turnover (episode): 40.36%
   Turnover (step): mean=40.357% | p95=57.259% | max=76.717%
   Turnover vs target: target=35.000% | exceed_rate=68.6% | mean_excess=7.230%
   Raw/Executed turnover: raw_mean=40.357% | executed/raw=1.000

[RAND] Run 6/20 (Seed=106147):
   Start Date: 2022-08-18 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +49.95%
   Annualized Return: +14.46%
   Sharpe: 0.8092
   Volatility (Ann.): 15.81%
   Max DD: 19.31%
   Turnover (episode): 41.45%
   Turnover (step): mean=41.453% | p95=59.821% | max=88.985%
   Turnover vs target: target=35.000% | exceed_rate=70.5% | mean_excess=8.203%
   Raw/Executed turnover: raw_mean=41.453% | executed/raw=1.000

[RAND] Run 7/20 (Seed=106148):
   Start Date: 2022-08-16 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +46.86%
   Annualized Return: +13.67%
   Sharpe: 0.7615
   Volatility (Ann.): 15.90%
   Max DD: 20.25%
   Turnover (episode): 40.89%
   Turnover (step): mean=40.892% | p95=58.035% | max=80.530%
   Turnover vs target: target=35.000% | exceed_rate=72.3% | mean_excess=7.625%
   Raw/Executed turnover: raw_mean=40.892% | executed/raw=1.000

[RAND] Run 8/20 (Seed=106149):
   Start Date: 2022-01-03 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +38.14%
   Annualized Return: +11.37%
   Sharpe: 0.6076
   Volatility (Ann.): 16.82%
   Max DD: 23.71%
   Turnover (episode): 40.15%
   Turnover (step): mean=40.148% | p95=58.193% | max=72.506%
   Turnover vs target: target=35.000% | exceed_rate=67.7% | mean_excess=6.962%
   Raw/Executed turnover: raw_mean=40.148% | executed/raw=1.000

[RAND] Run 9/20 (Seed=106150):
   Start Date: 2022-02-07 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +38.67%
   Annualized Return: +11.51%
   Sharpe: 0.6227
   Volatility (Ann.): 16.55%
   Max DD: 25.45%
   Turnover (episode): 40.73%
   Turnover (step): mean=40.725% | p95=60.756% | max=81.912%
   Turnover vs target: target=35.000% | exceed_rate=67.9% | mean_excess=7.751%
   Raw/Executed turnover: raw_mean=40.725% | executed/raw=1.000

[RAND] Run 10/20 (Seed=106151):
   Start Date: 2022-04-26 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +36.08%
   Annualized Return: +10.81%
   Sharpe: 0.5591
   Volatility (Ann.): 17.63%
   Max DD: 17.94%
   Turnover (episode): 40.64%
   Turnover (step): mean=40.640% | p95=58.017% | max=80.905%
   Turnover vs target: target=35.000% | exceed_rate=68.6% | mean_excess=7.332%
   Raw/Executed turnover: raw_mean=40.640% | executed/raw=1.000

[RAND] Run 11/20 (Seed=106152):
   Start Date: 2022-05-25 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +35.49%
   Annualized Return: +10.66%
   Sharpe: 0.5750
   Volatility (Ann.): 16.57%
   Max DD: 18.87%
   Turnover (episode): 40.72%
   Turnover (step): mean=40.721% | p95=58.727% | max=76.012%
   Turnover vs target: target=35.000% | exceed_rate=69.9% | mean_excess=7.321%
   Raw/Executed turnover: raw_mean=40.721% | executed/raw=1.000

[RAND] Run 12/20 (Seed=106153):
   Start Date: 2022-06-15 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +64.17%
   Annualized Return: +17.97%
   Sharpe: 0.9626
   Volatility (Ann.): 16.55%
   Max DD: 18.14%
   Turnover (episode): 40.17%
   Turnover (step): mean=40.171% | p95=58.036% | max=77.238%
   Turnover vs target: target=35.000% | exceed_rate=66.2% | mean_excess=6.992%
   Raw/Executed turnover: raw_mean=40.171% | executed/raw=1.000

[RAND] Run 13/20 (Seed=106154):
   Start Date: 2022-02-03 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +29.51%
   Annualized Return: +9.00%
   Sharpe: 0.4840
   Volatility (Ann.): 16.58%
   Max DD: 23.49%
   Turnover (episode): 40.81%
   Turnover (step): mean=40.807% | p95=57.576% | max=80.682%
   Turnover vs target: target=35.000% | exceed_rate=69.3% | mean_excess=7.600%
   Raw/Executed turnover: raw_mean=40.807% | executed/raw=1.000

[RAND] Run 14/20 (Seed=106155):
   Start Date: 2022-08-16 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +47.34%
   Annualized Return: +13.79%
   Sharpe: 0.7584
   Volatility (Ann.): 16.16%
   Max DD: 20.59%
   Turnover (episode): 40.22%
   Turnover (step): mean=40.219% | p95=57.369% | max=65.232%
   Turnover vs target: target=35.000% | exceed_rate=67.7% | mean_excess=7.111%
   Raw/Executed turnover: raw_mean=40.219% | executed/raw=1.000

[RAND] Run 15/20 (Seed=106156):
   Start Date: 2022-03-28 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +22.61%
   Annualized Return: +7.03%
   Sharpe: 0.3723
   Volatility (Ann.): 16.71%
   Max DD: 23.67%
   Turnover (episode): 40.64%
   Turnover (step): mean=40.641% | p95=57.975% | max=75.182%
   Turnover vs target: target=35.000% | exceed_rate=69.1% | mean_excess=7.366%
   Raw/Executed turnover: raw_mean=40.641% | executed/raw=1.000

[RAND] Run 16/20 (Seed=106157):
   Start Date: 2022-02-09 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +35.19%
   Annualized Return: +10.57%
   Sharpe: 0.5720
   Volatility (Ann.): 16.52%
   Max DD: 22.78%
   Turnover (episode): 40.55%
   Turnover (step): mean=40.552% | p95=58.585% | max=77.561%
   Turnover vs target: target=35.000% | exceed_rate=69.5% | mean_excess=7.444%
   Raw/Executed turnover: raw_mean=40.552% | executed/raw=1.000

[RAND] Run 17/20 (Seed=106158):
   Start Date: 2022-01-20 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +31.60%
   Annualized Return: +9.59%
   Sharpe: 0.5125
   Volatility (Ann.): 16.76%
   Max DD: 23.78%
   Turnover (episode): 40.58%
   Turnover (step): mean=40.577% | p95=59.383% | max=83.719%
   Turnover vs target: target=35.000% | exceed_rate=69.9% | mean_excess=7.333%
   Raw/Executed turnover: raw_mean=40.577% | executed/raw=1.000

[RAND] Run 18/20 (Seed=106159):
   Start Date: 2022-03-28 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +12.38%
   Annualized Return: +3.97%
   Sharpe: 0.1985
   Volatility (Ann.): 16.53%
   Max DD: 26.97%
   Turnover (episode): 41.29%
   Turnover (step): mean=41.289% | p95=58.439% | max=73.478%
   Turnover vs target: target=35.000% | exceed_rate=71.9% | mean_excess=7.815%
   Raw/Executed turnover: raw_mean=41.289% | executed/raw=1.000

[RAND] Run 19/20 (Seed=106160):
   Start Date: 2022-05-11 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +57.23%
   Annualized Return: +16.28%
   Sharpe: 0.8540
   Volatility (Ann.): 17.08%
   Max DD: 18.35%
   Turnover (episode): 40.33%
   Turnover (step): mean=40.333% | p95=58.687% | max=89.791%
   Turnover vs target: target=35.000% | exceed_rate=68.6% | mean_excess=7.248%
   Raw/Executed turnover: raw_mean=40.333% | executed/raw=1.000

[RAND] Run 20/20 (Seed=106161):
   Start Date: 2022-08-02 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +46.17%
   Annualized Return: +13.49%
   Sharpe: 0.7506
   Volatility (Ann.): 15.93%
   Max DD: 21.52%
   Turnover (episode): 41.07%
   Turnover (step): mean=41.075% | p95=59.148% | max=79.053%
   Turnover vs target: target=35.000% | exceed_rate=70.2% | mean_excess=7.687%
   Raw/Executed turnover: raw_mean=41.075% | executed/raw=1.000

================================================================================
SUMMARY: STOCHASTIC EVALUATION STATISTICS
================================================================================

Total Return (%):
   Mean: +38.52%
   Std:  14.22%
   Min:  +12.38%
   Max:  +64.17%

Annualized Return (%):
   Mean: +11.35%
   Std:  3.84%
   Min:  +3.97%
   Max:  +17.97%

Sharpe Ratio (annualized):
   Mean: 0.6116
   Std:  0.2142
   Min:  0.1985
   Max:  0.9626

Volatility (Ann. %):
   Mean: +16.60%
   Std:  0.52%
   Min:  +15.81%
   Max:  +17.67%

Max Drawdown (%):
   Mean: 21.51%
   Std:  2.73%
   Min:  17.94%
   Max:  26.97%

Turnover (%):
   Mean: 40.61%
   Std:  0.40%

Turnover Step Detail (%):
   Mean(step mean): 40.606%
   Mean(step p95):  58.286%
   Mean(step max):  78.412%
   Mean exceed rate: 69.0%
   Mean excess over target: 7.394%
   Mean executed/raw ratio: 1.000

================================================================================
LOADING CUSTOM CHECKPOINT: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00004_shp1p259
================================================================================
[OK] Found actor weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00004_shp1p259_actor.weights.h5
[OK] Found critic weights: /content/tcn_tape_vectorized_version_clean/tcn_fusion_results/high_watermark_checkpoints/exp6_tape_hw_ep00004_shp1p259_critic.weights.h5
🏗️ Recreating evaluation environments...
   🧭 Checkpoint architecture: TCN_FUSION (attention=True, fusion=True, source=path)
   🧱 Eval TCN stack: filters=[64, 96, 128, 128, 128] | kernel=5 | dilations=[1, 2, 4, 8, 16] | dropout=0.15
   🧩 Eval fusion core: embed=128 | heads=4 | dropout=0.1
   🔀 Eval mixer (A4): enabled=False | layers=1 | expansion=2.0 | dropout=0.1
   🎯 Eval alpha head (A3): dims=[128, 64] | dropout=0.05
   🧭 Eval fusion v2 cross-attn: asset_identity=True | context_cross_attn=False | ctx_heads=4 | ctx_dropout=0.1 | per_asset_alpha_head=True
   [BRAIN] Eval recurrent memory: enabled=False | units=64 | dropout=0.1
   [GLOBE] Eval regime conditioning: enabled=True | mode=film | hidden_dim=32 | dropout=0.05
   [DOWN] Eval distributional critic: enabled=True | num_quantiles=17
   🎛️ Eval dirichlet: activation=exp_tanh | temperature=1.2 | adaptive_temp=False | adaptive_base=1.0 | adaptive_slope=0.0 | adaptive_range=[0.8, 2.5] | alpha_cap=16.0 | epsilon={'max': 0.2, 'min': 0.02}
   🧷 Eval dual-head: enabled=False | blend_schedule=[{'threshold': 0, 'rho': 0.35}, {'threshold': 30000, 'rho': 0.55}, {'threshold': 60000, 'rho': 0.7}] | eval_rho_det=0.9 | eval_rho_stoch=0.6 | use_constraints=False
   🧷 Eval dual-head consistency coef: 0.0
[TOOL] Building models before loading weights...
   [OK] Models built successfully
📂 Loading checkpoint weights...
   [OK] Weights loaded successfully
   🎯 Deterministic eval policy modes: ['mean']
   🎯 Stochastic eval policy mode:     sample

================================================================================
DETERMINISTIC EVALUATION (det_mean)
================================================================================

📊 DETERMINISTIC TEST RESULTS:
   Eval Track: det_mean
   Start Date: 2022-01-03
   Market Regime: Rate Hikes / Tech Correction (2022)
   Episode Length: 918 days (3.64 years)
   Final Portfolio Value: $193,016.65
   Total Return: +93.02%
   Annualized Return: +19.78%
   Sharpe Ratio: 1.0446 (annualized)
   Sortino Ratio: 1.4934 (annualized)
   Max Drawdown: 19.96%
   Volatility (Ann.): 16.75%
   Turnover: 0.73%
   Win Rate: 54.53%
   Diagnostics: action_uniques=918, alpha<=1 frac=0.091, argmax_alpha_uniques=8

================================================================================
STOCHASTIC EVALUATIONS (Random Start = True, 20 Runs)
================================================================================

[RAND] Run 1/20 (Seed=106142):
   Start Date: 2022-08-23 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +64.16%
   Annualized Return: +17.97%
   Sharpe: 0.9865
   Volatility (Ann.): 16.07%
   Max DD: 19.32%
   Turnover (episode): 40.61%
   Turnover (step): mean=40.613% | p95=57.598% | max=87.447%
   Turnover vs target: target=35.000% | exceed_rate=68.5% | mean_excess=7.401%
   Raw/Executed turnover: raw_mean=40.613% | executed/raw=1.000

[RAND] Run 2/20 (Seed=106143):
   Start Date: 2022-04-29 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +30.41%
   Annualized Return: +9.25%
   Sharpe: 0.4830
   Volatility (Ann.): 17.37%
   Max DD: 18.50%
   Turnover (episode): 40.58%
   Turnover (step): mean=40.579% | p95=58.224% | max=71.022%
   Turnover vs target: target=35.000% | exceed_rate=71.0% | mean_excess=7.303%
   Raw/Executed turnover: raw_mean=40.579% | executed/raw=1.000

[RAND] Run 3/20 (Seed=106144):
   Start Date: 2022-04-14 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +29.95%
   Annualized Return: +9.12%
   Sharpe: 0.4732
   Volatility (Ann.): 17.53%
   Max DD: 19.07%
   Turnover (episode): 40.34%
   Turnover (step): mean=40.337% | p95=57.628% | max=79.163%
   Turnover vs target: target=35.000% | exceed_rate=67.4% | mean_excess=7.260%
   Raw/Executed turnover: raw_mean=40.337% | executed/raw=1.000

[RAND] Run 4/20 (Seed=106145):
   Start Date: 2022-03-30 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +12.35%
   Annualized Return: +3.96%
   Sharpe: 0.1972
   Volatility (Ann.): 16.99%
   Max DD: 25.33%
   Turnover (episode): 41.50%
   Turnover (step): mean=41.502% | p95=58.947% | max=75.116%
   Turnover vs target: target=35.000% | exceed_rate=73.0% | mean_excess=7.994%
   Raw/Executed turnover: raw_mean=41.502% | executed/raw=1.000

[RAND] Run 5/20 (Seed=106146):
   Start Date: 2022-06-21 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +47.77%
   Annualized Return: +13.90%
   Sharpe: 0.7535
   Volatility (Ann.): 16.47%
   Max DD: 21.65%
   Turnover (episode): 41.08%
   Turnover (step): mean=41.080% | p95=59.082% | max=78.112%
   Turnover vs target: target=35.000% | exceed_rate=68.9% | mean_excess=7.870%
   Raw/Executed turnover: raw_mean=41.080% | executed/raw=1.000

[RAND] Run 6/20 (Seed=106147):
   Start Date: 2022-08-18 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +35.62%
   Annualized Return: +10.69%
   Sharpe: 0.5920
   Volatility (Ann.): 15.99%
   Max DD: 18.06%
   Turnover (episode): 40.42%
   Turnover (step): mean=40.421% | p95=57.191% | max=68.533%
   Turnover vs target: target=35.000% | exceed_rate=71.8% | mean_excess=7.033%
   Raw/Executed turnover: raw_mean=40.421% | executed/raw=1.000

[RAND] Run 7/20 (Seed=106148):
   Start Date: 2022-08-16 | Regime: Rate Hikes / Tech Correction (2022)
   Days Traded: 756 (3.00 years)
   Total Return: +42.67%
   Annualized Return: +12.58%

,prefix,det_sharpe,sto_sharpe_mean,sto_sharpe_std,sto_return_mean_pct,sto_mdd_mean_pct
0,/content/tcn_tape_vectorized_version_clean/tcn...,1.044581,0.621843,0.189013,39.257935,20.826741
1,/content/tcn_tape_vectorized_version_clean/tcn...,1.044581,0.611593,0.214199,38.515229,21.509074
2,/content/tcn_tape_vectorized_version_clean/tcn...,1.008787,-0.062290,0.240692,-0.121749,23.835598